### ISSUE TITLE
As a student, I need to set up time tracking in Harvest

### ISSUE THREAD

**Issue by fluxsauce** [fluxsauce/site_audit#10]
- [x] Use invite to sign up for Harvest
- [x] Populate time logged in the existing spreadsheet into Harvest
- [x] Log time spent interviewing agencies
- [x] Reply to this issue when complete so I can verify

**Comment by fluxsauce** [comment]
Hi @shivanshuag , please complete this prior to starting development.

**Comment by shivanshuag** [comment]
Hi @fluxsauce, I have completed this. please verify

**Comment by fluxsauce** [comment]
Very good! Only thing that's missing is the time spent interviewing Kalamuna, I don't see that listed? I'd consider that research.

**Comment by shivanshuag** [comment]
It was listed under meeting. I have changed it to research

**Comment by fluxsauce** [comment]
Hm, my filters must have been slightly wrong, I'm seeing it all now! Thank you, good job!
